BMS0432
Fix the web server hang under FreeBSD.  Symptomology is that you can't
connect to it and top shows ntop in a 'bpf' state.  Packets are being
processed.  Oh, and ntop runs fine (without problem) under gdb....

If you have no clue what that all means, don't use the option.
If you have a clue, then read the stuff in the man page to determine if you
need this run time option.  There's also a comment in globals-defines.h
worth a look if you use the --set-pcap-nonblocking option and see packet losses.

********************************************************************
* Thanks to Stanley Hopcroft [Stanley.Hopcroft@IPAustralia.Gov.AU] *
* for helping identify the problem, tons of primary research,      *
* debugging and testing!                                           *
*                                                                  *
* (Understand that we've been working on this on and off since     *
*  September 2003 - Stanley is a real trooper)                     *
********************************************************************

-----Burton

PS: I really, really, really, hope this fixes it for good!

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1330,7 +1330,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-SCRIPTVER="v2.2.99.013-2004-01-28"
+SCRIPTVER="v2.2.99.014-2004-02-02"
 
 umask 002
 # Add the stamp file to the list of files AC keeps track of,
@@ -8755,6 +8755,68 @@ if test $ac_cv_lib_pcap_pcap_lib_version = yes; then
 
 cat >>confdefs.h <<_ACEOF
 #define HAVE_PCAP_LIB_VERSION 1
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking for pcap_setnonblock in -lpcap" >&5
+echo $ECHO_N "checking for pcap_setnonblock in -lpcap... $ECHO_C" >&6
+if test "${ac_cv_lib_pcap_pcap_setnonblock+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpcap  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pcap_setnonblock ();
+int
+main ()
+{
+pcap_setnonblock ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pcap_pcap_setnonblock=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pcap_pcap_setnonblock=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pcap_pcap_setnonblock" >&5
+echo "${ECHO_T}$ac_cv_lib_pcap_pcap_setnonblock" >&6
+if test $ac_cv_lib_pcap_pcap_setnonblock = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_PCAP_SETNONBLOCK 1
 _ACEOF
 
 fi
