Add a --with-rrd-root option (like all the others) to ./configure
-----Burton (ref 153)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1039,6 +1039,7 @@ Optional Packages:
   --with-gd-root=DIR          GD source tree located in DIR
   --with-libpng-root=DIR      PNGLIB source tree located in DIR
   --with-zlib-root=DIR        ZLIB source tree located in DIR
+  --with-rrd-root=DIR         RRD located in DIR
   +----------------------------------------------------------------------------+
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-pic              try to use only PIC/non-PIC objects default=use both
@@ -2240,6 +2241,15 @@ else
   ZLIB_ROOT=
 fi;
 
+
+# Check whether --with-rrd-root or --without-rrd-root was given.
+if test "${with_rrd_root+set}" = set; then
+  withval="$with_rrd_root"
+  RRD_ROOT="$withval"
+else
+  RRD_ROOT=
+fi;
+
 # Check whether --enable-showoses or --disable-showoses was given.
 if test "${enable_showoses+set}" = set; then
   enableval="$enable_showoses"
@@ -2308,7 +2318,7 @@ else
         echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
     else
-        grep '1\.7$' /tmp/automake.$$ > /dev/null
+        grep '1\.[67]$' /tmp/automake.$$ > /dev/null
         rc=$?
         if test ".${rc}" = ".0"; then
             echo "$as_me:$LINENO: result: no" >&5
@@ -6465,7 +6475,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6468 "configure"' > conftest.$ac_ext
+  echo '#line 6478 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7001,7 +7011,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:7004: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:7014: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8794,7 +8804,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8797 "configure"
+#line 8807 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8892,7 +8902,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8895 "configure"
+#line 8905 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -27094,26 +27104,318 @@ fi
     fi
 fi
 
+if test ".${RRD_ROOT}" != "." &&
+   test ! -d ${RRD_ROOT}; then
+    echo
+    echo "*******************************************************************"
+    echo "*"
+    echo "* ERROR:    1. You specified a non-existent directory for the"
+    echo "*              --with-rrd-root option."
+    echo "*"
+    echo "*>>> Continuing without the --with-rrd-root option"
+    echo "*"
+    echo "*    ./configure will complete successfully but rrd may be disabled"
+    echo "*"
+    echo "*???     1. Correct the --with-rrd-root value and rerun ./configure"
+    echo "*"
+    echo "*******************************************************************"
+    echo
+    RRD_ROOT=
+fi
+
 echo "$as_me:$LINENO: checking for rrd" >&5
 echo $ECHO_N "checking for rrd... $ECHO_C" >&6
-if test ".${ac_cv_lib_rrd_rrd_create}" != ".yes"; then
-    echo "$as_me:$LINENO: result: error" >&5
-echo "${ECHO_T}error" >&6
-    echo
-    echo "*******************************************************************"
-    echo "*"
-    echo "* WARNING:  1. librrd has not been found."
-    echo "*"
-    echo "*>>>    The rrdPlugin will not be built."
-    echo "*"
-    echo "*???     1. Install RRDtool from http://www.rrdtool.org/"
-    echo "*??? and 2. rerun ./configure"
-    echo "*"
-    echo "*******************************************************************"
-    echo
-else
-    echo "$as_me:$LINENO: result: ok" >&5
+ac_disable_rrd="no"
+
+if test ".${ac_cv_header_rrd_h}"        = ".yes" &&
+   test ".${ac_cv_lib_rrd_rrd_create}"   = ".yes"; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD 1
+_ACEOF
+
+    if test ".${RRD_ROOT}" != "."; then
+        echo "$as_me:$LINENO: result: ok" >&5
 echo "${ECHO_T}ok" >&6
+        echo
+        echo "*******************************************************************"
+        echo "*"
+        echo "* NOTE:  You specified (or implied) --with-rrd-root.  However,"
+        echo "*        a version was found in a standard location."
+        echo "*"
+        echo "*       Since this version will be used anyway,"
+        echo "*"
+        echo "*******************************************************************"
+        echo
+        RRD_ROOT=
+    else
+        echo "$as_me:$LINENO: result: ok (standard location)" >&5
+echo "${ECHO_T}ok (standard location)" >&6
+    fi
+elif test ".${RRD_ROOT}" = "."; then
+    echo "$as_me:$LINENO: result: not found in standard location, no --with-rrd-root, testing further..." >&5
+echo "${ECHO_T}not found in standard location, no --with-rrd-root, testing further..." >&6
+    echo "$as_me:$LINENO: checking for rrd header" >&5
+echo $ECHO_N "checking for rrd header... $ECHO_C" >&6
+    if test -d /usr &&
+       test -d /usr/include &&
+       test -r /usr/include/rrd.h; then
+        echo "$as_me:$LINENO: result: ok, found in /usr/include" >&5
+echo "${ECHO_T}ok, found in /usr/include" >&6
+        INCS="${INCS} -I/usr/include"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD_H 1
+_ACEOF
+
+    elif test -d /usr &&
+       test -d /usr/local &&
+       test -d /usr/local/include &&
+       test -r /usr/local/include/rrd.h; then
+        echo "$as_me:$LINENO: result: ok, found in /usr/local/include" >&5
+echo "${ECHO_T}ok, found in /usr/local/include" >&6
+        INCS="${INCS} -I/usr/local/include"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD_H 1
+_ACEOF
+
+    else
+        echo "$as_me:$LINENO: result: error" >&5
+echo "${ECHO_T}error" >&6
+        echo
+        echo "*******************************************************************"
+        echo "*"
+        echo "* ERROR:  1. We were unable to find the header rrd.h in the"
+        echo "*            standard location."
+        echo "*"
+        echo "*     and 2. You did not specify an alternate location"
+        echo "*            via --with-rrd-root"
+        echo "*"
+        echo "*     and 3. We also tested the following:"
+        echo "*"
+        echo "*                /usr/include"
+        echo "*                /usr/local/include"
+        echo "*"
+        echo "*>>> ./configure continues, rrd will not be available."
+        echo "*"
+        echo "*???     1. Rerun ./configure with a corrected --with-rrd-root"
+        echo "*???  or 2. Install rrd and rerun ./configure"
+        echo "*"
+        echo "*******************************************************************"
+        echo
+        ac_disable_rrd="yes"
+    fi
+    if test ".${ac_disable_rrd}" = ".yes"; then
+        nop="yes"
+    else
+        echo "$as_me:$LINENO: checking for rrd library" >&5
+echo $ECHO_N "checking for rrd library... $ECHO_C" >&6
+        if test -d /usr &&
+           test -d /usr/lib &&
+           (test -r /usr/lib/librrd.so ||
+            test -r /usr/lib/librrd.a); then
+            echo "$as_me:$LINENO: result: ok, found in /usr/lib" >&5
+echo "${ECHO_T}ok, found in /usr/lib" >&6
+            RRDLIB="${RRDLIB} -L/usr/lib -lrrd"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD 1
+_ACEOF
+
+        elif test -d /usr &&
+           test -d /usr/local &&
+           test -d /usr/local/lib &&
+           (test -r /usr/local/lib/librrd.so ||
+            test -r /usr/local/lib/librrd.a); then
+            echo "$as_me:$LINENO: result: ok, found in /usr/local/lib" >&5
+echo "${ECHO_T}ok, found in /usr/local/lib" >&6
+            RRDLIB="${RRDLIB} -L/usr/local/lib -lrrd"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD 1
+_ACEOF
+
+        else
+            echo "$as_me:$LINENO: result: error" >&5
+echo "${ECHO_T}error" >&6
+            echo
+            echo "*******************************************************************"
+            echo "*"
+            echo "* ERROR:  1. We were unable to compile a test program for"
+            echo "*            rrd_create() against -lrrd."
+            echo "*"
+            echo "*     and 2. You did not specify an alternate location"
+            echo "*            via --with-rrd-root"
+            echo "*"
+            echo "*     and 3. We were unable to find librrd.so or librrd.a"
+            echo "*            via a manual search of"
+            echo "*"
+            echo "*                /usr/lib"
+            echo "*                /usr/local/lib"
+            echo "*"
+            echo "*>>> ./configure continues, rrd will not be available."
+            echo "*"
+            echo "*???     1. Rerun ./configure with a corrected --with-rrd-root"
+            echo "*???  or 2. Install rrd and rerun ./configure"
+            echo "*"
+            echo "*******************************************************************"
+            echo
+            ac_disable_rrd="yes"
+        fi
+    fi
+else
+    echo "$as_me:$LINENO: result: not found in standard location, testing further..." >&5
+echo "${ECHO_T}not found in standard location, testing further..." >&6
+
+    echo "$as_me:$LINENO: checking for rrd header" >&5
+echo $ECHO_N "checking for rrd header... $ECHO_C" >&6
+
+    RRD_ROOT=`(cd ${RRD_ROOT} && pwd)`
+    if test -d ${RRD_ROOT} &&
+       test -r ${RRD_ROOT}/rrd.h; then
+        echo "$as_me:$LINENO: result: ok, rrd.h found in ${RRD_ROOT}" >&5
+echo "${ECHO_T}ok, rrd.h found in ${RRD_ROOT}" >&6
+        INCS="${INCS} -I${RRD_ROOT}"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD_H 1
+_ACEOF
+
+    elif test -d ${RRD_ROOT} &&
+       test -d ${RRD_ROOT}/include &&
+       test -r ${RRD_ROOT}/include/rrd.h; then
+        echo "$as_me:$LINENO: result: ok, rrd.h found in ${RRD_ROOT}/include" >&5
+echo "${ECHO_T}ok, rrd.h found in ${RRD_ROOT}/include" >&6
+        INCS="${INCS} -I${RRD_ROOT}/include"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD_H 1
+_ACEOF
+
+    else
+        echo "$as_me:$LINENO: result: error" >&5
+echo "${ECHO_T}error" >&6
+        echo
+        echo "*******************************************************************"
+        echo "*"
+        echo "* ERROR:  1. We were unable to find the header rrd.h in the"
+        echo "*            standard location or the alternate location you"
+        echo "*            specified by --with-rrd-root"
+        echo "*"
+        echo "*>>> ./configure continues, rrd will not be available."
+        echo "*"
+        echo "*???     1. Rerun ./configure with a corrected --with-rrd-root"
+        echo "*???  or 2. Install rrd and rerun ./configure"
+        echo "*"
+        echo "*******************************************************************"
+        echo
+        ac_disable_rrd="yes"
+    fi
+
+    if test ".${ac_disable_rrd}" != ".yes"; then
+                        oLIBS="${LIBS}"
+        # Expansion of NTOP_APPEND_LIBS(${RRD_ROOT}/lib, )
+    case "${DEFINEOS}" in
+      DARWIN )
+          LIBS="$LIBS -L${RRD_ROOT}/lib -L${RRD_ROOT}/lib/lib"
+          ;;
+      * )
+          LIBS="$LIBS -L${RRD_ROOT}/lib"
+          ;;
+    esac
+    if test "." != "."; then
+        LIBS="$LIBS -l"
+    fi
+# Finished expansion of NTOP_APPEND_LIBS()
+
+        echo "$as_me:$LINENO: checking for rrd_update in -lrrd" >&5
+echo $ECHO_N "checking for rrd_update in -lrrd... $ECHO_C" >&6
+if test "${ac_cv_lib_rrd_rrd_update+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lrrd  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char rrd_update ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+rrd_update ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_rrd_rrd_update=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_rrd_rrd_update=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_rrd_rrd_update" >&5
+echo "${ECHO_T}$ac_cv_lib_rrd_rrd_update" >&6
+if test $ac_cv_lib_rrd_rrd_update = yes; then
+
+            RRDLIB="${RRDLIB} -L${RRD_ROOT}/lib -lrrd"
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_RRD 1
+_ACEOF
+
+
+else
+
+            echo
+            echo "*******************************************************************"
+            echo "*"
+            echo "* ERROR:  1. We were unable to compile a test program for"
+            echo "*            rrd_create() against -lrrd in the standard"
+            echo "*            location nor in the alternate location you"
+            echo "*            specified by --with-rrd-root"
+            echo "*"
+            echo "*>>> ./configure continues, rrd will not be available."
+            echo "*"
+            echo "*???     1. Rerun ./configure with a corrected --with-rrd-root"
+            echo "*???  or 2. Install rrd and rerun ./configure"
+            echo "*"
+            echo "*******************************************************************"
+            echo
+            ac_disable_rrd="yes"
+
+fi
+
+        LIBS="${oLIBS}"
+    fi
 fi
 
 echo
