Added fix for pcap_open_dead

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5346,6 +5346,68 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for pcap_open_dead in -lpcap" >&5
+echo $ECHO_N "checking for pcap_open_dead in -lpcap... $ECHO_C" >&6
+if test "${ac_cv_lib_pcap_pcap_open_dead+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpcap  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pcap_open_dead ();
+int
+main ()
+{
+pcap_open_dead ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pcap_pcap_open_dead=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pcap_pcap_open_dead=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pcap_pcap_open_dead" >&5
+echo "${ECHO_T}$ac_cv_lib_pcap_pcap_open_dead" >&6
+if test $ac_cv_lib_pcap_pcap_open_dead = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_PCAP_OPEN_DEAD 1
+_ACEOF
+
+fi
+
 
 for ac_header in pcap.h
 do
@@ -7715,7 +7777,7 @@ test x"$silent" = xyes && libtool_flags="$libtool_flags --silent"
 case "$host" in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7718 "configure"' > conftest.$ac_ext
+  echo '#line 7780 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15897,6 +15959,7 @@ fi
 done
 
 
+if test ".${ac_enable_xmldump}" = ".yes"; then
 
 
 for ac_header in glib.h glibconfig.h
@@ -16324,6 +16387,7 @@ fi
 
 done
 
+fi
 
 echo "$as_me:$LINENO: checking for pid_t" >&5
 echo $ECHO_N "checking for pid_t... $ECHO_C" >&6
