BMS0440
Add logic to support /etc/auth.conf (FreeBSD and ???) which changes
the crypt() call to something 'more advanced'.

Add test in configure for crypt_get_format().

If this feature is available, ntop will add '3' records to the ntop_pw.db
which indicate the setting of crypt_set_format() to use for the specific
user.  ntop then changes the setting before calling crypt() to revalidate
the password.

Note that there is a subtle issue here - because you need to be admin to change
most things, the value used across ntop will TEND to follow the value when the
admin userid was created, rather than the current setting in /etc/auth.conf.

If that causes you major pain, then recreate the password database (so all
users have the new crypt()), or run ntop ... -A to force a reset of the
admin record.  That will give you an ntop_pw.db like this:

'        1tester'(  7): '991aNDDm9rsg2'( 13)
'        3tester'(  7): 'des'(  3)
'         3admin'(  6): 'md5'(  3)
'         1admin'(  6): '$1$99$zo3ud4buZmwpcejmzdr6C.'( 28)

where admin is now md5, but tester is still des.  Any new users will be
md5, and if admin resets tester's password, then tester will switch over
to md5.

Weird stuff, eh...

-----Burton

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1330,7 +1330,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-SCRIPTVER="v2.2.99.014-2004-02-02"
+SCRIPTVER="v2.2.99.015-2004-02-10"
 
 umask 002
 # Add the stamp file to the list of files AC keeps track of,
@@ -19015,6 +19015,135 @@ fi
 fi
 
 
+echo "$as_me:$LINENO: checking for crypt_get_format_get_format in -lc" >&5
+echo $ECHO_N "checking for crypt_get_format_get_format in -lc... $ECHO_C" >&6
+if test "${ac_cv_lib_c_crypt_get_format_get_format+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char crypt_get_format_get_format ();
+int
+main ()
+{
+crypt_get_format_get_format ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_c_crypt_get_format_get_format=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_c_crypt_get_format_get_format=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_c_crypt_get_format_get_format" >&5
+echo "${ECHO_T}$ac_cv_lib_c_crypt_get_format_get_format" >&6
+if test $ac_cv_lib_c_crypt_get_format_get_format = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBC 1
+_ACEOF
+
+  LIBS="-lc $LIBS"
+
+else
+
+echo "$as_me:$LINENO: checking for crypt_get_format in -lcrypt" >&5
+echo $ECHO_N "checking for crypt_get_format in -lcrypt... $ECHO_C" >&6
+if test "${ac_cv_lib_crypt_crypt_get_format+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcrypt  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char crypt_get_format ();
+int
+main ()
+{
+crypt_get_format ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_crypt_crypt_get_format=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_crypt_crypt_get_format=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_crypt_crypt_get_format" >&5
+echo "${ECHO_T}$ac_cv_lib_crypt_crypt_get_format" >&6
+if test $ac_cv_lib_crypt_crypt_get_format = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCRYPT 1
+_ACEOF
+
+  LIBS="-lcrypt $LIBS"
+
+fi
+
+fi
+
+
 echo "$as_me:$LINENO: checking for getopt_long in -lc" >&5
 echo $ECHO_N "checking for getopt_long in -lc... $ECHO_C" >&6
 if test "${ac_cv_lib_c_getopt_long+set}" = set; then
@@ -24474,6 +24603,14 @@ echo "$as_me: error: Unable to continue... aborting ./configure" >&2;}
 else
     echo "$as_me:$LINENO: result: ok" >&5
 echo "${ECHO_T}ok" >&6
+fi
+if (test ".${ac_cv_lib_c_crypt_get_format}" = ".yes") ||
+   (test ".${ac_cv_lib_crypt_crypt_get_format}" = ".yes"); then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_CRYPTGETFORMAT 1
+_ACEOF
+
 fi
 
 echo "$as_me:$LINENO: checking for dynamic load module" >&5
