Bleep it.
I've removed the --enable-automake171 flag in favor of an explicit test for
matching auto* tools versions.  That is, there is a file distributed (new)
with ntop - autotoolversions - that has the exact version of the three
auto* tools (automake, autoconf and libtool) used to create the versions
of the various generated files (configure, Makefile, etc.) which are
distributed with ntop.

If those versions do not match - EXACTLY - then the first time you run
./configure, ntop will delete and recreate ALL of the generated files
and update autotoolversions.

You will then need to run ./configure a SECOND time to do the actual
configuration!

But, this should eliminate the problems with conflicting versions.

It does not change the minimum required versions:

    automake 1.6+
    autoconf 2.5x+
    libtool 1.3+ (we say 1.4+, but it does seem to work just fine with 1.3.4)

-----Burton (ref 188)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1015,7 +1015,6 @@ Optional Features:
   --enable-xmldump            Enable xml-based data dump default=disabled
   --enable-showoses           display OS Support information.
   --enable-iknowbetter        Override WILLFAIL
-  --enable-automake171        Override automake 1.7.1 abort
   +----------------------------------------------------------------------------+
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
@@ -1422,7 +1421,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-SCRIPTVER="v1.002-2002-11-25"
+SCRIPTVER="v1.100-2003-01-29"
 
 umask 002
 # Add the stamp file to the list of files AC keeps track of,
@@ -1456,6 +1455,111 @@ echo
 echo "Configuring ${PACKAGE_NAME} according to your request(s):"
 echo "   ./configure ${CONFIGURE_PARAMETERS}"
 echo
+
+if test -f /tmp/autotoolversions; then
+     rm -f /tmp/autotoolversions
+fi
+automake --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }'  >/tmp/autotoolversions
+autoconf --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+libtool --version | head -n 1  | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+
+touch autotoolversions
+diff -q autotoolversions /tmp/autotoolversions 2>/dev/null
+rc=$?
+
+if test ".${rc}" = ".1"; then
+    echo
+    echo "*******************************************************************"
+    echo "*"
+    echo "* WARNING: Auto* tools installed on this host differ from the ones"
+    echo "*          that the ntop distribution uses:"
+    echo "*"
+    echo "* This host:"
+    cat /tmp/autotoolversions
+    echo "*"
+    echo "* ntop distribution:"
+    cat autotoolversions
+    echo "*"
+    echo "*>>> Version conflicts may cause configure/compile/link problems."
+    echo "*"
+    echo "*>>> We are going to:"
+    echo "*>>>     1. delete the existing generated files"
+    echo "*>>>     2. use the auto* tools to recreate them"
+    echo "*                (if you do not have automake, autoconf and libtool"
+    echo "*                 intalled, this will fail)"
+    echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
+    echo "*"
+    echo "*    Please, tell the ntop-dev mailing list if there are problems..."
+    echo "*"
+    echo "*******************************************************************"
+    echo
+    echo "1. delete the existing generated files:"
+    for i in acinclude.m4 \
+             aclocal.m4 \
+             Makefile.in \
+             config.h.in \
+             configure \
+             Makefile; do
+        if test -f $i; then
+             echo "     .... $i"
+             rm -f $i
+        fi
+    done
+    echo "    done!"
+    echo
+    echo "2. use the auto* tools to recreate them:"
+    echo "    .... cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
+    cat acinclude.m4.ntop libtool.m4.in > acinclude.m4
+    rc=$?
+    if test ".${rc}" != ".0"; then
+        echo
+        echo "*******************************************************************"
+        echo "*"
+        echo "* ERROR: Unable to run cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
+        echo "*"
+        echo "*    We are going to give up."
+        echo "*"
+        echo "*>>> Please correct the problem and rerun"
+        echo "*"
+        echo "*******************************************************************"
+        echo
+        exit 1
+    fi
+    for i in aclocal \
+             autoheader \
+             "automake --gnu --copy --add-missing" \
+             autoconf; do
+        echo "    .... $i"
+        $i
+        rc=$?
+        if test ".${rc}" != ".0"; then
+            echo
+            echo "*******************************************************************"
+            echo "*"
+            echo "* ERROR: Unable to run $i"
+            echo "*"
+            echo "*    We are going to give up."
+            echo "*"
+            echo "*>>> Please correct the problem with the auto* tools and rerun"
+            echo "*"
+            echo "*******************************************************************"
+            echo
+            exit 1
+        fi
+    done
+
+    cp -f /tmp/autotoolversions autotoolversions
+
+    if test -f /tmp/autotoolversions; then
+        rm -f tmp/autotoolversions
+    fi
+
+    echo
+    echo
+    echo "Now, rerun ./configure"
+    echo
+    exit 1
+fi
 
 
 
@@ -2397,14 +2501,6 @@ else
   ac_willfailoverride="no"
 fi;
 
-# Check whether --enable-automake171 or --disable-automake171 was given.
-if test "${enable_automake171+set}" = set; then
-  enableval="$enable_automake171"
-  ac_automake171="yes"
-else
-  ac_automake171="no"
-fi;
-
 # Check whether --enable-void or --disable-void was given.
 if test "${enable_void+set}" = set; then
   enableval="$enable_void"
@@ -2416,153 +2512,6 @@ if test "${with_void+set}" = set; then
   withval="$with_void"
 
 fi;
-
-if ! test -f automake171.ok; then
-    automake --version | grep ^automake >/tmp/automake.$$
-    echo "$as_me:$LINENO: checking automake version for 1.7.1/1.6.3 conflict..." >&5
-echo $ECHO_N "checking automake version for 1.7.1/1.6.3 conflict...... $ECHO_C" >&6
-    grep '1\.5$' /tmp/automake.$$ > /dev/null
-    rc=$?
-    if test ".${rc}" = ".0"; then
-        echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-    else
-        grep '1\.6\.[123]$' /tmp/automake.$$ > /dev/null
-        rc=$?
-        if test ".${rc}" = ".0"; then
-            echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-        else
-            grep '1\.[67]$' /tmp/automake.$$ > /dev/null
-            rc=$?
-            if test ".${rc}" = ".0"; then
-                echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-            else
-                grep '1\.7\.[0-9]$' /tmp/automake.$$ > /dev/null
-                rc=$?
-                if test ".${rc}" = ".0"; then
-                    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-                    echo
-                    echo "*******************************************************************"
-                    echo "*"
-                    echo "* WARNING: Attempting to configure with automake 1.7.x"
-                    echo "*"
-                    cat /tmp/automake.$$
-                    echo "*"
-                    echo "*>>> There is a known problem - and probably an error message above."
-                    echo "*"
-                    if test ".${ac_automake171}" = ".yes"; then
-                        echo "*    The --enable-automake171 flag is set, so we continue."
-                    else
-                        echo "*>>> We are going to:"
-                        echo "*>>>     1. delete the existing generated files"
-                        echo "*>>>     2. use the auto* tools to recreate them"
-                        echo "*                (if you do not have automake, autoconf and libtool"
-                        echo "*                 intalled, this will fail)"
-                        echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
-                    fi
-                    echo "*"
-                    echo "*    Please, tell the ntop-dev mailing list if there are problems..."
-                    echo "*"
-                    echo "*******************************************************************"
-                    echo
-                    if test ".${ac_automake171}" != ".yes"; then
-                        echo "1. delete the existing generated files:"
-                        for i in acinclude.m4 \
-                                 aclocal.m4 \
-                                 Makefile.in \
-                                 config.h.in \
-                                 configure \
-                                 Makefile; do
-                            if test -f $i; then
-                                 echo "     .... $i"
-                                 rm -f $i
-                            fi
-                        done
-                        echo "    done!"
-                        echo
-                        echo "2. use the auto* tools to recreate them:"
-                        echo "    .... cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
-                        cat acinclude.m4.ntop libtool.m4.in > acinclude.m4
-                        rc=$?
-                        if test ".${rc}" != ".0"; then
-                            echo
-                            echo "*******************************************************************"
-                            echo "*"
-                            echo "* ERROR: Unable to run cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
-                            echo "*"
-                            echo "*    We are going to give up."
-                            echo "*"
-                            echo "*>>> Please correct the problem and rerun"
-                            echo "*"
-                            echo "*******************************************************************"
-                            echo
-                            exit 1
-                        fi
-                        for i in aclocal \
-                                 autoheader \
-                                 "automake --gnu --copy --add-missing" \
-                                 autoconf; do
-                            echo "    .... $i"
-                            $i
-                            rc=$?
-                            if test ".${rc}" != ".0"; then
-                                echo
-                                echo "*******************************************************************"
-                                echo "*"
-                                echo "* ERROR: Unable to run $i"
-                                echo "*"
-                                echo "*    We are going to give up."
-                                echo "*"
-                                echo "*>>> Please correct the problem with the auto* tools and rerun"
-                                echo "*"
-                                echo "*******************************************************************"
-                                echo
-                                exit 1
-                            fi
-                        done
-                        echo
-                        echo
-                        echo "Now, rerun ./configure"
-                        echo
-                        touch automake171.ok
-                        exit 1
-                    fi
-                else
-                    echo "$as_me:$LINENO: result: maybe" >&5
-echo "${ECHO_T}maybe" >&6
-                    echo
-                    echo "*******************************************************************"
-                    echo "*"
-                    echo "* WARNING: Attempting to configure with automake > 1.7.1"
-                    echo "*"
-                    cat /tmp/automake.$$
-                    echo "*"
-                    echo "*>>> This has never been tested."
-                    echo "*>>> It will probably fail."
-                    echo "*"
-                    if test ".${ac_automake171}" = ".yes"; then
-                         echo "*    You claim to know better, so good luck..."
-                         echo "*"
-                    fi
-                    echo "*    You are welcome to try - but please, keep the ntop-dev"
-                    echo "*    mailing list updated with your successes or failures..."
-                    echo "*"
-                    echo "*******************************************************************"
-                    echo
-                    if test ".${ac_automake171}" != ".yes"; then
-                         exit 1
-                    fi
-                fi
-            fi
-        fi
-    fi
-else
-    echo "Automake 1.7.1 OK flag found ... continuing"
-fi
-rm -f /tmp/automake.$$
 
 # Set constants and defaults
 AS=
@@ -6604,7 +6553,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6607 "configure"' > conftest.$ac_ext
+  echo '#line 6556 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7140,7 +7089,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:7143: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:7092: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8933,7 +8882,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8936 "configure"
+#line 8885 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9031,7 +8980,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9034 "configure"
+#line 8983 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -48,7 +48,7 @@ dnl>       into the stamp.
 dnl>
 AC_INIT([ntop],[2.1.56pre])
 AC_PREREQ([2.50])
-SCRIPTVER="v1.002-2002-11-25"
+SCRIPTVER="v1.100-2003-01-29"
 
 dnl>
 dnl> generate the config header
@@ -81,6 +81,119 @@ echo
 echo "Configuring ${PACKAGE_NAME} according to your request(s):"
 echo "   ./configure ${CONFIGURE_PARAMETERS}"
 echo
+
+dnl>
+dnl> Check versions of autotools...
+dnl>
+dnl>      We know that all of the 1.6.x [1..3] versions of automake work ok
+dnl>      and the 2.5x [1..7] of autoconf work ok too.
+dnl>      So we could compress them to save a few recreations, but that's 
+dnl>      then got to be maintained.  So exact match or recreate...
+dnl>
+if test -f /tmp/autotoolversions; then
+     rm -f /tmp/autotoolversions
+fi
+automake --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }'  >/tmp/autotoolversions
+autoconf --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+libtool --version | head -n 1  | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+
+touch autotoolversions
+diff -q autotoolversions /tmp/autotoolversions 2>/dev/null
+rc=$?
+
+if test ".${rc}" = ".1"; then
+    echo
+    echo "*******************************************************************"
+    echo "*"
+    echo "* WARNING: Auto* tools installed on this host differ from the ones"
+    echo "*          that the ntop distribution uses:"
+    echo "*"
+    echo "* This host:"
+    cat /tmp/autotoolversions
+    echo "*"
+    echo "* ntop distribution:"
+    cat autotoolversions
+    echo "*"
+    echo "*>>> Version conflicts may cause configure/compile/link problems."
+    echo "*"
+    echo "*>>> We are going to:"
+    echo "*>>>     1. delete the existing generated files"
+    echo "*>>>     2. use the auto* tools to recreate them"
+    echo "*                (if you do not have automake, autoconf and libtool"
+    echo "*                 intalled, this will fail)"
+    echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
+    echo "*"
+    echo "*    Please, tell the ntop-dev mailing list if there are problems..."
+    echo "*"
+    echo "*******************************************************************"
+    echo
+    echo "1. delete the existing generated files:"
+    for i in acinclude.m4 \
+             aclocal.m4 \
+             Makefile.in \
+             config.h.in \
+             configure \
+             Makefile; do
+        if test -f $i; then
+             echo "     .... $i"
+             rm -f $i
+        fi
+    done
+    echo "    done!"
+    echo
+    echo "2. use the auto* tools to recreate them:"
+    echo "    .... cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
+    cat acinclude.m4.ntop libtool.m4.in > acinclude.m4
+    rc=$?
+    if test ".${rc}" != ".0"; then
+        echo
+        echo "*******************************************************************"
+        echo "*"
+        echo "* ERROR: Unable to run cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
+        echo "*"
+        echo "*    We are going to give up."
+        echo "*"
+        echo "*>>> Please correct the problem and rerun"
+        echo "*"
+        echo "*******************************************************************"
+        echo
+        exit 1
+    fi
+    for i in aclocal \
+             autoheader \
+             "automake --gnu --copy --add-missing" \
+             autoconf; do
+        echo "    .... $i"
+        $i
+        rc=$?
+        if test ".${rc}" != ".0"; then
+            echo
+            echo "*******************************************************************"
+            echo "*"
+            echo "* ERROR: Unable to run $i"
+            echo "*"
+            echo "*    We are going to give up."
+            echo "*"
+            echo "*>>> Please correct the problem with the auto* tools and rerun"
+            echo "*"
+            echo "*******************************************************************"
+            echo
+            exit 1
+        fi
+    done
+
+    cp -f /tmp/autotoolversions autotoolversions
+
+    if test -f /tmp/autotoolversions; then
+        rm -f tmp/autotoolversions
+    fi
+
+    echo
+    echo
+    echo "Now, rerun ./configure"
+    echo
+    exit 1
+fi
 
 dnl> autoheader stuff...just ignore
 AH_TEMPLATE([HAVE_INT16_T],   [Define for int16 typedef])
@@ -361,157 +474,10 @@ AC_ARG_ENABLE(iknowbetter,
               ac_willfailoverride="yes",
               ac_willfailoverride="no")
 
-AC_ARG_ENABLE(automake171,
-              [  --enable-automake171        Override automake 1.7.1 abort],
-              ac_automake171="yes",
-              ac_automake171="no")
-
 AC_ARG_ENABLE(void,
               [  +----------------------------------------------------------------------------+])
 AC_ARG_WITH(void,
               [  +----------------------------------------------------------------------------+])
-
-dnl> Automake version problem test...
-if ! test -f automake171.ok; then
-    automake --version | grep ^automake >/tmp/automake.$$
-    AC_MSG_CHECKING([automake version for 1.7.1/1.6.3 conflict...])
-    grep '1\.5$' /tmp/automake.$$ > /dev/null
-    rc=$?
-    if test ".${rc}" = ".0"; then
-        AC_MSG_RESULT(no)
-    else
-        grep '1\.6\.[[123]]$' /tmp/automake.$$ > /dev/null
-        rc=$?
-        if test ".${rc}" = ".0"; then
-            AC_MSG_RESULT(no)
-        else
-            grep '1\.[[67]]$' /tmp/automake.$$ > /dev/null
-            rc=$?
-            if test ".${rc}" = ".0"; then
-                AC_MSG_RESULT(no)
-            else
-                grep '1\.7\.[[0-9]]$' /tmp/automake.$$ > /dev/null
-                rc=$?
-                if test ".${rc}" = ".0"; then
-                    AC_MSG_RESULT(yes)
-                    echo
-                    echo "*******************************************************************"
-                    echo "*"
-                    echo "* WARNING: Attempting to configure with automake 1.7.x"
-                    echo "*"
-                    cat /tmp/automake.$$
-                    echo "*"
-                    echo "*>>> There is a known problem - and probably an error message above."
-                    echo "*"
-                    if test ".${ac_automake171}" = ".yes"; then
-                        echo "*    The --enable-automake171 flag is set, so we continue."
-                    else
-                        echo "*>>> We are going to:"
-                        echo "*>>>     1. delete the existing generated files"
-                        echo "*>>>     2. use the auto* tools to recreate them"
-                        echo "*                (if you do not have automake, autoconf and libtool"
-                        echo "*                 intalled, this will fail)"
-                        echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
-                    fi
-                    echo "*"
-                    echo "*    Please, tell the ntop-dev mailing list if there are problems..."
-                    echo "*"
-                    echo "*******************************************************************"
-                    echo
-                    if test ".${ac_automake171}" != ".yes"; then
-                        echo "1. delete the existing generated files:"
-                        for i in acinclude.m4 \
-                                 aclocal.m4 \
-                                 Makefile.in \
-                                 config.h.in \
-                                 configure \
-                                 Makefile; do
-                            if test -f $i; then
-                                 echo "     .... $i"
-                                 rm -f $i
-                            fi
-                        done
-                        echo "    done!"
-                        echo
-                        echo "2. use the auto* tools to recreate them:"
-                        echo "    .... cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
-                        cat acinclude.m4.ntop libtool.m4.in > acinclude.m4
-                        rc=$?
-                        if test ".${rc}" != ".0"; then
-                            echo
-                            echo "*******************************************************************"
-                            echo "*"
-                            echo "* ERROR: Unable to run cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
-                            echo "*"
-                            echo "*    We are going to give up."
-                            echo "*"
-                            echo "*>>> Please correct the problem and rerun"
-                            echo "*"
-                            echo "*******************************************************************"
-                            echo
-                            exit 1
-                        fi
-                        for i in aclocal \
-                                 autoheader \
-                                 "automake --gnu --copy --add-missing" \
-                                 autoconf; do
-                            echo "    .... $i"
-                            $i
-                            rc=$?
-                            if test ".${rc}" != ".0"; then
-                                echo
-                                echo "*******************************************************************"
-                                echo "*"
-                                echo "* ERROR: Unable to run $i"
-                                echo "*"
-                                echo "*    We are going to give up."
-                                echo "*"
-                                echo "*>>> Please correct the problem with the auto* tools and rerun"
-                                echo "*"
-                                echo "*******************************************************************"
-                                echo
-                                exit 1
-                            fi
-                        done
-                        echo
-                        echo
-                        echo "Now, rerun ./configure"
-                        echo
-                        touch automake171.ok
-                        exit 1
-                    fi
-                else
-                    AC_MSG_RESULT(maybe)
-                    echo
-                    echo "*******************************************************************"
-                    echo "*"
-                    echo "* WARNING: Attempting to configure with automake > 1.7.1"
-                    echo "*"
-                    cat /tmp/automake.$$
-                    echo "*"
-                    echo "*>>> This has never been tested."
-                    echo "*>>> It will probably fail."
-                    echo "*"
-                    if test ".${ac_automake171}" = ".yes"; then
-                         echo "*    You claim to know better, so good luck..."
-                         echo "*"
-                    fi
-                    echo "*    You are welcome to try - but please, keep the ntop-dev"
-                    echo "*    mailing list updated with your successes or failures..."
-                    echo "*"
-                    echo "*******************************************************************"
-                    echo
-                    if test ".${ac_automake171}" != ".yes"; then
-                         exit 1
-                    fi
-                fi
-            fi
-        fi
-    fi
-else
-    echo "Automake 1.7.1 OK flag found ... continuing"
-fi
-rm -f /tmp/automake.$$
 
 # Set constants and defaults
 AS=
