Removed --disable-mt from ntop
As of 3.1.50, ntop requires POSIX threads.


-----Burton (ref 590)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -45,12 +45,12 @@ dnl>   Edit the version # in the AC_INIT line to roll the version.
 dnl>   Edit NTOP_VERSION_EXTRA to put something extra (e.g. SourceForge rpm version"
 dnl>       into the stamp.
 dnl>
-AC_INIT([ntop],[3.1.2])
+AC_INIT([ntop],[3.1.50])
 
 dnl> The prereq is really 2.53, i.e. automake 1.6, but Darwin uses 2.52...
 AC_PREREQ([2.52])
 
-SCRIPTVER="v3.1.005-2005-05-11"
+SCRIPTVER="v3.1.050-2005-05-28"
 
 dnl>
 dnl> generate the config header
@@ -145,6 +145,33 @@ OBJEXT=o
 
 NTOPCONFIGDEBUG_SETTINGS([ntop defaults])
 
+AC_ARG_ENABLE(void,
+              [  +--ntop:---------------------------------------------------------------------+])
+AC_ARG_ENABLE(mt,
+              [  --disable-mt                No longer valid],
+[
+          echo
+          echo "*******************************************************************"
+          echo "*"
+          echo "* ERROR: --disable-mt is no longer valid."
+          echo "*"
+          echo "*    As of version 3.1.50, ntop requires POSIX threads"
+          echo "*"
+          echo "*>>> Please rerun ./configure without --disable-mt"
+          echo "*"
+          echo "*******************************************************************"
+          echo
+          exit 1
+],[])
+dnl> Test before we use it, below
+AC_ARG_ENABLE(iknowbetter,
+              [  --enable-iknowbetter        Override WILLFAIL],
+              ac_willfailoverride="yes",
+              ac_willfailoverride="no")
+
+AC_ARG_ENABLE(void,
+              [  +----------------------------------------------------------------------------+])
+
 # Checks for programs.
 
 AC_PROG_AWK
@@ -235,12 +262,6 @@ case "${target}:${CC}" in
         AC_CHECK_TOOL(LIBTOOL, libtool)
         ;;
 esac
-
-dnl> Test before we use it, below
-AC_ARG_ENABLE(iknowbetter,
-              [  --enable-iknowbetter        Override WILLFAIL],
-              ac_willfailoverride="yes",
-              ac_willfailoverride="no")
 
 echo -n "  Checking libtool version..."
 case "${target}:${CC}" in
@@ -625,11 +646,6 @@ AC_ARG_ENABLE(void,
 AC_ARG_WITH(void,
               [  +--external-packages:--------------------------------------------------------+])
 
-AC_ARG_ENABLE(mt,
-              [  --disable-mt                disable multithread support [[default=enabled]]],
-              ac_disable_multithread="yes",
-              ac_disable_multithread="no")
-
 AC_ARG_WITH(ssl,
               [  --without-ssl               disable HTPPS support [[default=enabled]]],
               ac_disable_openssl="yes",
@@ -955,17 +971,6 @@ dnl> To be listed, must be in top 10 of www.distrowatch.org's 6 months charts
         RELEASE="8"
       ;;
 
-    *-*-solaris2.5*:* )
-        NOTE1="Trying Solaris 2.5 configuration stuff from ntop 2.1."
-        DEFINEOS="SOLARIS";   STATUS="UNTESTED"
-        AC_DEFINE_UNQUOTED(CFG_NEED_INET_ATON,
-                           1,
-                           [Solaris 2.5: private implementation of inet_aton])
-        AC_DEFINE_UNQUOTED(CFG_NEED_GETDOMAINNAME,
-                           1,
-                           [OS lacks getdomainname function.])
-      ;;
-
     *-*-solaris*:* )
         DEFINEOS="SOLARIS";   STATUS="UNTESTED"
       ;;
@@ -1013,16 +1018,9 @@ dnl> To be listed, must be in top 10 of www.distrowatch.org's 6 months charts
     *-*-netbsd*1.5*:gcc* )
         VERIFIED1="2.1.90:2003-03-29:Burton Strauss <burton@ntopsupport.com:1.6"
         VERIFIED2="2.1.51:2002-10-23:Burton Strauss <burton@ntopsupport.com:1.5.3 w/ updated auto* tools"
-        NOTE1="Single Threaded only."
+        NOTE1="With ANY of the threads packages, you are on your own!"
         DEFINEOS="NETBSD"
-        if test ".${ac_disable_multithread}" = ".yes"; then
-            STATUS="SUPPORTED"
-            NOTE2="NetBSD 1.6 requires the UPDATED libpcap in the packages"
-            NOTE3="  If you see a missing pcap_open_dead, you forgot to update!"
-        else
-            STATUS="WILLFAIL"
-            NOTE2="With ANY of the threads packages, you are on your own!"
-        fi
+        STATUS="WILLFAIL"
       ;;
 
     *-*-netbsd*:* )
@@ -1594,15 +1592,6 @@ echo "-------------------------------------------------------------------"
 echo
 echo "   **Handling your --enable and --disable requests**"
 echo
-
-echo
-echo "Multithread?"
-if test ".${ac_disable_multithread}" = ".yes"; then
-    echo "    ...Disabled via ./configure command line option --disable-mt"
-    multithread_mode="disabled (Single Threaded) via --disable-mt"
-else
-    echo "    ...(Default) Requested if available. Disable via ./configure command line option --disable-mt."
-fi
 
 echo
 echo "SSL?"
@@ -2190,13 +2179,6 @@ AC_CHECK_LIB(pthread, pthread_create, , [
 ])
 AC_CHECK_LIB(posix4, sem_init)
 
-dnl> regex.c
-AC_CHECK_LIB([c], 
-             [re_search],
-             AC_DEFINE_UNQUOTED(HAVE_REGEX, 
-                                1, 
-                                [regex lib is defined inside -lc for regex.c]))
-
 dnl> TCP Wrappers
 dnl>  This is a problem - the test sets HAVE_LIBWRAP, which is the flag in ntop
 dnl>  But we haven't processed --with-tcpwrap yet. So we dummy this out until
@@ -2209,8 +2191,6 @@ AC_CHECK_LIB([xml2], [xmlCheckVersion])
 AC_CHECK_LIB([gdome], [gdome_di_saveDocToFile])
 
 dnl> Functions and types
-AC_FUNC_ALLOCA
-
 AC_FUNC_FORK
 AC_PROG_GCC_TRADITIONAL
 dnl> do not use AC_FUNC_MALLOC ... because we have our own replacement...
@@ -2222,7 +2202,6 @@ AC_FUNC_STRFTIME
 AC_FUNC_VPRINTF
 
 AC_CHECK_FUNCS([alarm])
-AC_CHECK_FUNCS([ctime_r])
 AC_CHECK_FUNCS([endpwent])
 AC_CHECK_FUNCS([gethostbyaddr gethostbyname gethostname])
 dnl> Note, we've already tested for gethostbyaddr_r to find it's library, above.
@@ -2231,11 +2210,9 @@ AC_CHECK_FUNCS([gethostbyaddr_r])
 AC_CHECK_FUNCS([getipnodebyaddr])
 AC_CHECK_FUNCS([getpass])
 AC_CHECK_FUNCS([gettimeofday])
-AC_CHECK_FUNCS([inet_ntoa])
 AC_CHECK_FUNCS([localtime_r])
 AC_CHECK_FUNCS([memchr memset])
 AC_CHECK_FUNCS([putenv])
-AC_CHECK_FUNCS([re_comp regcomp])
 AC_CHECK_FUNCS([sched_yield])
 AC_CHECK_FUNCS([select socket])
 AC_CHECK_FUNCS([snprintf])
@@ -2253,8 +2230,6 @@ AC_CHECK_FUNCS([uname])
 
 dnl> Test for strtok_r (we have our own defn if it's not available)C_CHECK_FUNCS([strtok_r])
 AC_CHECK_FUNCS([strtok_r])
-dnl> Following used by regex.c only
-AC_CHECK_FUNCS([bzero])
 
 case "${CC}" in
   *gcc* )
@@ -2395,46 +2370,37 @@ echo "   **Testing Optional libraries and headers**"
 echo
 
 dnl> Multithreaded:
-if test ".${ac_disable_multithread}" != ".yes"; then
-    AC_MSG_CHECKING([for Multithreading])
+AC_MSG_CHECKING([for Multithreading])
 
-    if test ".${ac_cv_header_pthread_h}"             != ".yes" ||
-       (test ".${ac_cv_lib_pthread_pthread_create}"  != ".yes" &&
-        test ".${ac_cv_lib_pthreads_pthread_create}" != ".yes" &&
-        test ".${ac_cv_lib_c_r_pthread_create}"      != ".yes"); then
-        AC_MSG_WARN(error)
-        ac_disable_multithread="yes"
-        echo
-        echo "*******************************************************************"
-        echo "*"
-        echo "* WARNING:  We are unable to find a header/library required"
-        echo "*           to support multi-threading."
-        echo "*"
-        echo "*>>>    ntop will be built single threaded."
-        echo "*       This is only minimally supported."
-        echo "*"
-        echo "*    Missing:"
-        echo "*           (yes means it was found, no means it was not found)"
-        echo "*"
-        echo "*              pthread.h...${ac_cv_header_pthread_h}"
-        echo "*              pthread_create() in -lpthread...${ac_cv_lib_pthread_pthread_create} -lpthreads...${ac_cv_lib_pthreads_pthread_create} -lc_r...${ac_cv_lib_c_r_pthread_create}"
-        echo "*"
-        echo "*???     1. Install the necessary headers and libraries."
-        echo "*???    and rerun ./configure"
-        echo "*"
-        echo "*******************************************************************"
-        echo
-        HAS_WARNING="yes"
-    fi
-
-    if test ".${ac_disable_multithread}" != ".yes"; then
-        AC_MSG_RESULT(ok)
-        AC_DEFINE_UNQUOTED(CFG_MULTITHREADED,        1, [Enable/disable multithread support])
-        multithread_mode="enabled"
-    else
-        multithread_mode="disabled (Single Threaded)"
-    fi
+if test ".${ac_cv_header_pthread_h}"             != ".yes" ||
+   (test ".${ac_cv_lib_pthread_pthread_create}"  != ".yes" &&
+    test ".${ac_cv_lib_pthreads_pthread_create}" != ".yes" &&
+    test ".${ac_cv_lib_c_r_pthread_create}"      != ".yes"); then
+    AC_MSG_WARN(error)
+    echo
+    echo "*******************************************************************"
+    echo "*"
+    echo "* ERROR:    We are unable to find a header/library required"
+    echo "*           to support multi-threading."
+    echo "*"
+    echo "*>>>    ntop will not be configured"
+    echo "*"
+    echo "*    Missing:"
+    echo "*           (yes means it was found, no means it was not found)"
+    echo "*"
+    echo "*              pthread.h...${ac_cv_header_pthread_h}"
+    echo "*              pthread_create() in -lpthread...${ac_cv_lib_pthread_pthread_create} -lpthreads...${ac_cv_lib_pthreads_pthread_create} -lc_r...${ac_cv_lib_c_r_pthread_create}"
+    echo "*"
+    echo "*>>> No way to proceed."
+    echo "*"
+    echo "*???     1. Install the necessary headers and libraries."
+    echo "*???    and rerun ./configure"
+    echo "*"
+    echo "*******************************************************************"
+    echo
+    AC_MSG_ERROR(Unable to continue... aborting ./configure)
 fi
+AC_MSG_RESULT(ok)
 
 dnl> openSSL:
 if test ".${ac_disable_openssl}" != ".yes"; then
@@ -2861,7 +2827,6 @@ echo "Defines                 : ${DEFS}"
 echo "Loader (ldflags)        : ${LDFLAGS}"
 echo "Include path            : ${INCS}"
 echo "System Libs             : ${LIBS}"
-echo "MultiThread mode        : ${multithread_mode}"
 echo "Locale                  : ${LOCALEDIR}"
 echo 
 echo "External packages:"
