This is a configure.in / configure fix to handle a bug in automake 1.7.1
ntop distributes configure (and other files) created using autoconf 2.53
and automake 1.6.3.  These files work with automake 1.6.x and 1.7.
But not automake 1.7.1.  (automake 1.5 is unknown, but suspected NOT to work).

It's a deliberate change on the part of automake, that breaks ANY chance
of distributing ONE set of files which can be used by all ntop users -
whatever version of the auto* tools they have...  <GRRR />

Reference: http://mail.gnu.org/pipermail/automake-patches/2002-January/000559.html

I can not trap it cleanly, because the call to automake which reports the problem
happens before the FIRST generated line in ./configure.

We can't just fix up the one file - they all have to be build by a consistent set
of tools, and if there are problems, then the "make" step fails.

What this patch does is to detect the problem, perform the best mitigation
possible and then abort ./configure.  This happens well after the automake
error messages, but there is a pretty clear error box displayed.

If the auto* tools execute cleanly (thus creating a 1.7.1 set in the
ntop source directory), the user is instructed to rerun ./configure,
"with whatever parameters you normally use plus --enable-automake171".

-----Burton (ref 151)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1013,6 +1013,7 @@ Optional Features:
   --enable-ignoresigpipe      Ignore SIGPIPE errors default=do not ignore
   --enable-showoses           display OS Support information.
   --enable-iknowbetter        Override WILLFAIL
+  --enable-automake171        Override automake 1.7.1 abort
   +----------------------------------------------------------------------------+
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
@@ -2272,6 +2273,14 @@ else
   ac_willfailoverride="no"
 fi;
 
+# Check whether --enable-automake171 or --disable-automake171 was given.
+if test "${enable_automake171+set}" = set; then
+  enableval="$enable_automake171"
+  ac_automake171="yes"
+else
+  ac_automake171="no"
+fi;
+
 # Check whether --enable-void or --disable-void was given.
 if test "${enable_void+set}" = set; then
   enableval="$enable_void"
@@ -2283,6 +2292,148 @@ if test "${with_void+set}" = set; then
   withval="$with_void"
 
 fi;
+
+automake --version | grep ^automake >/tmp/automake.$$
+echo "$as_me:$LINENO: checking automake version for 1.7.1/1.6.3 conflict..." >&5
+echo $ECHO_N "checking automake version for 1.7.1/1.6.3 conflict...... $ECHO_C" >&6
+grep '1\.5$' /tmp/automake.$$ > /dev/null
+rc=$?
+if test ".${rc}" = ".0"; then
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+else
+    grep '1\.6\.[123]$' /tmp/automake.$$ > /dev/null
+    rc=$?
+    if test ".${rc}" = ".0"; then
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    else
+        grep '1\.7$' /tmp/automake.$$ > /dev/null
+        rc=$?
+        if test ".${rc}" = ".0"; then
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        else
+            grep '1\.7\.[0-9]$' /tmp/automake.$$ > /dev/null
+            rc=$?
+            if test ".${rc}" = ".0"; then
+                echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                echo
+                echo "*******************************************************************"
+                echo "*"
+                echo "* WARNING: Attempting to configure with automake 1.7.x"
+                echo "*"
+                cat /tmp/automake.$$
+                echo "*"
+                echo "*>>> There is a known problem - and probably an error message above."
+                echo "*"
+                if test ".${ac_automake171}" = ".yes"; then
+                    echo "*    The --enable-automake171 flag is set, so we continue."
+                else
+                    echo "*>>> We are going to:"
+                    echo "*>>>     1. delete the existing generated files"
+                    echo "*>>>     2. use the auto* tools to recreate them"
+                    echo "*                (if you do not have automake, autoconf and libtool"
+                    echo "*                 intalled, this will fail)"
+                    echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
+                fi
+                echo "*"
+                echo "*    Please, tell the ntop-dev mailing list if there are problems..."
+                echo "*"
+                echo "*******************************************************************"
+                echo
+                if test ".${ac_automake171}" != ".yes"; then
+                    echo "1. delete the existing generated files:"
+                    for i in acinclude.m4 \
+                             aclocal.m4 \
+                             Makefile.in \
+                             config.h.in \
+                             configure \
+                             Makefile; do
+                        if test -f $i; then
+                             echo "     .... $i"
+                             rm -f $i
+                        fi
+                    done
+                    echo "    done!"
+                    echo
+                    echo "2. use the auto* tools to recreate them:"
+                    echo "    .... cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
+                    cat acinclude.m4.ntop libtool.m4.in > acinclude.m4
+                    rc=$?
+                    if test ".${rc}" != ".0"; then
+                        echo
+                        echo "*******************************************************************"
+                        echo "*"
+                        echo "* ERROR: Unable to run cat acinclude.m4.ntop libtool.m4.in > acinclude.m4"
+                        echo "*"
+                        echo "*    We are going to give up."
+                        echo "*"
+                        echo "*>>> Please correct the problem and rerun"
+                        echo "*"
+                        echo "*******************************************************************"
+                        echo
+                        exit 1
+                    fi
+                    for i in aclocal \
+                             autoheader \
+                             "automake --gnu --copy --add-missing" \
+                             autoconf; do
+                        echo "    .... $i"
+                        $i
+                        rc=$?
+                        if test ".${rc}" != ".0"; then
+                            echo
+                            echo "*******************************************************************"
+                            echo "*"
+                            echo "* ERROR: Unable to run $i"
+                            echo "*"
+                            echo "*    We are going to give up."
+                            echo "*"
+                            echo "*>>> Please correct the problem with the auto* tools and rerun"
+                            echo "*"
+                            echo "*******************************************************************"
+                            echo
+                            exit 1
+                        fi
+                    done
+                    echo
+                    echo
+                    echo "Now, rerun ./configure with whatever parameters you normally use plus --enable-automake171"
+                    echo
+                    exit 1
+                fi
+            else
+                echo "$as_me:$LINENO: result: maybe" >&5
+echo "${ECHO_T}maybe" >&6
+                echo
+                echo "*******************************************************************"
+                echo "*"
+                echo "* WARNING: Attempting to configure with automake > 1.7.1"
+                echo "*"
+                cat /tmp/automake.$$
+                echo "*"
+                echo "*>>> This has never been tested."
+                echo "*>>> It will probably fail."
+                echo "*"
+                if test ".${ac_automake171}" = ".yes"; then
+                     echo "*    You claim to know better, so good luck..."
+                     echo "*"
+                fi
+                echo "*    You are welcome to try - but please, keep the ntop-dev"
+                echo "*    mailing list updated with your successes or failures..."
+                echo "*"
+                echo "*******************************************************************"
+                echo
+                if test ".${ac_automake171}" != ".yes"; then
+                     exit 1
+                fi
+            fi
+        fi
+    fi
+fi
+rm -f /tmp/automake.$$
 
 # Set constants and defaults
 AS=
@@ -6314,7 +6465,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6317 "configure"' > conftest.$ac_ext
+  echo '#line 6468 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6850,7 +7001,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6853: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:7004: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8643,7 +8794,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8646 "configure"
+#line 8797 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8741,7 +8892,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8744 "configure"
+#line 8895 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
