Minor fixups beyond BMS0188...
Add explict test for autoconf version.
Move the automake/autoconf tests to the very top.
Test for awk up front.
Fixup autotoolversions test so it runs under awk as well as gawk.

Understood that this removes the (minute) possibility of having ./configure
work without the auto* tools installed at all, and/or a down level version.
That only worked through blind dumb luck before, this locks it down.

S'be'it...

-----Burton (ref 194)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1421,7 +1421,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-SCRIPTVER="v1.100-2003-01-29"
+SCRIPTVER="v1.101-2003-01-31"
 
 umask 002
 # Add the stamp file to the list of files AC keeps track of,
@@ -1456,12 +1456,141 @@ echo "Configuring ${PACKAGE_NAME} according to your request(s):"
 echo "   ./configure ${CONFIGURE_PARAMETERS}"
 echo
 
+echo "*******************************************************************"
+echo "*                                                                 *"
+echo "* NOTICE:  I know you're used to ignoring output from ./configure *"
+echo "*                                                                 *"
+echo "*          ntop has a lot of complexity and interdependences.     *"
+echo "*                                                                 *"
+echo "*          Please, please AT LEAST read the stuff in these        *"
+echo "*          boxes!                                                 *"
+echo "*                                                                 *"
+echo "*>>> The ACTION taken is shown prefixed '>>>'                     *"
+echo "*                                                                 *"
+echo "*    If the ACTION is unacceptable,                               *"
+echo "*??? The REMEDIATION plan is shown prefixed with '???'            *"
+echo "*                                                                 *"
+echo "*******************************************************************"
+echo
+
+for ac_prog in gawk mawk nawk awk
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_AWK+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$AWK"; then
+  ac_cv_prog_AWK="$AWK" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_AWK="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+AWK=$ac_cv_prog_AWK
+if test -n "$AWK"; then
+  echo "$as_me:$LINENO: result: $AWK" >&5
+echo "${ECHO_T}$AWK" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$AWK" && break
+done
+
+
+
+echo "  Checking automake version..."
+automakeversion=`automake --version | grep ^automake | awk '{ print $4 }'`
+case "${automakeversion}" in
+    *1\.[0-5]*)
+        echo "*******************************************************************"
+        echo "*                                                                 *"
+        echo "*ERROR: ntop requires automake version 1.6 or newer...            *"
+        echo "*                                                                 *"
+        echo "*  You are executing ${automakeversion}"
+        echo "*                                                                 *"
+        echo "*>>>   Unable to proceed with your request, aborting ./configure! *"
+        echo "*                                                                 *"
+        echo "*???    Suggestion - Install a private copy of automake 1.6.3.    *"
+        echo "*???                 It's quite easy and does NOT require root:   *"
+        echo "*                                                                 *"
+        echo "*   Download automake 1.6.3 from gnu                              *"
+        echo "*     $ wget http://ftp.gnu.org/gnu/automake/automake-1.6.3.tar.gz*"
+        echo "*                                                                 *"
+        echo "*   Untar it                                                      *"
+        echo "*     $ tar xfvz automake-1.6.3.tar.gz                            *"
+        echo "*                                                                 *"
+        echo "*   Make it                                                       *"
+        echo "*     $ cd automake-1.6.3                                         *"
+        echo "*     $ ./configure --prefix=/home/<whatever>/automake163         *"
+        echo "*     $ make                                                      *"
+        echo "*     $ make install                                              *"
+        echo "*                                                                 *"
+        echo "*   Add it to your path.  Under bash do this:                     *"
+        echo "*     $ PATH=/home/<whatever>automake163/bin:\$PATH                *"
+        echo "*     $ export PATH                                               *"
+        echo "*                                                                 *"
+        echo "*******************************************************************"
+        exit 1
+        ;;
+esac
+echo "  Checking autoconf version..."
+case "${autoconfversion}" in
+    *2\.[0-4]*)
+        echo "*******************************************************************"
+        echo "*                                                                 *"
+        echo "*ERROR: ntop requires autoconf version 2.50 or newer...           *"
+        echo "*                                                                 *"
+        echo "*  You are executing ${autoconfversion}"
+        echo "*                                                                 *"
+        echo "*>>>   Unable to proceed with your request, aborting ./configure! *"
+        echo "*                                                                 *"
+        echo "*???    Suggestion - Install a private copy of autoconf 2.5x.     *"
+        echo "*???                 It's quite easy and does NOT require root:   *"
+        echo "*                                                                 *"
+        echo "*   Download autoconf 2.57 from gnu                               *"
+        echo "*     $ wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.57.tar.gz *"
+        echo "*                                                                 *"
+        echo "*   Untar it                                                      *"
+        echo "*     $ tar xfvz autoconf-2.57.tar.gz                             *"
+        echo "*                                                                 *"
+        echo "*   Make it                                                       *"
+        echo "*     $ cd autoconf-2.57                                          *"
+        echo "*     $ ./configure --prefix=/home/<whatever>/autoconf257         *"
+        echo "*     $ make                                                      *"
+        echo "*     $ make install                                              *"
+        echo "*                                                                 *"
+        echo "*   Add it to your path.  Under bash do this:                     *"
+        echo "*     $ PATH=/home/<whatever>autoconf257/bin:\$PATH                *"
+        echo "*     $ export PATH                                               *"
+        echo "*                                                                 *"
+        echo "*******************************************************************"
+        exit 1
+        ;;
+esac
+
 if test -f /tmp/autotoolversions; then
      rm -f /tmp/autotoolversions
 fi
-automake --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }'  >/tmp/autotoolversions
-autoconf --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
-libtool --version | head -n 1  | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+automake --version | head -n 1 | ${ac_cv_prog_AWK} '{ gsub(/\)/, "", $3); print "     " $3 " " $4 }'  >/tmp/autotoolversions
+autoconf --version | head -n 1 | ${ac_cv_prog_AWK} '{ gsub(/\)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+libtool --version | head -n 1  | ${ac_cv_prog_AWK} '{ gsub(/\)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
 
 touch autotoolversions
 diff -q autotoolversions /tmp/autotoolversions 2>/dev/null
@@ -1487,7 +1616,7 @@ if test ".${rc}" = ".1"; then
     echo "*>>>     2. use the auto* tools to recreate them"
     echo "*                (if you do not have automake, autoconf and libtool"
     echo "*                 intalled, this will fail)"
-    echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
+    echo "*>>>     3. tell you to rerun ./configure"
     echo "*"
     echo "*    Please, tell the ntop-dev mailing list if there are problems..."
     echo "*"
@@ -1555,10 +1684,15 @@ if test ".${rc}" = ".1"; then
     fi
 
     echo
-    echo
-    echo "Now, rerun ./configure"
+    echo "*******************************************************************"
+    echo "*                                                                 *"
+    echo "*   Now, rerun ./configure                                        *"
+    echo "*                                                                 *"
+    echo "*******************************************************************"
     echo
     exit 1
+else
+    echo "auto* tools are OK, continuing with ./configure"
 fi
 
 
@@ -1581,23 +1715,6 @@ fi
 
 
 
-
-echo "*******************************************************************"
-echo "*                                                                 *"
-echo "* NOTICE:  I know you're used to ignoring output from ./configure *"
-echo "*                                                                 *"
-echo "*          ntop has a lot of complexity and interdependences.     *"
-echo "*                                                                 *"
-echo "*          Please, please AT LEAST read the stuff in these        *"
-echo "*          boxes!                                                 *"
-echo "*                                                                 *"
-echo "*>>> The ACTION taken is shown prefixed '>>>'                     *"
-echo "*                                                                 *"
-echo "*    If the ACTION is unacceptable,                               *"
-echo "*??? The REMEDIATION plan is shown prefixed with '???'            *"
-echo "*                                                                 *"
-echo "*******************************************************************"
-echo
 
 
 
@@ -1860,46 +1977,6 @@ else
 echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
 fi
 
-for ac_prog in gawk mawk nawk awk
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_AWK+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$AWK"; then
-  ac_cv_prog_AWK="$AWK" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_AWK="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-AWK=$ac_cv_prog_AWK
-if test -n "$AWK"; then
-  echo "$as_me:$LINENO: result: $AWK" >&5
-echo "${ECHO_T}$AWK" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$AWK" && break
-done
-
 echo "$as_me:$LINENO: checking whether ${MAKE-make} sets \${MAKE}" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y,./+-,__p_,'`
@@ -2118,88 +2195,11 @@ else
 
     echo ""
     echo "depcomp missing... will install it in this ntop directory."
-    echo "  Checking automake version..."
-    automakeversion=`automake --version | grep ^automake | awk '{ print $4 }'`
-    case "${automakeversion}" in
-        *1\.[45]*)
-            echo "*******************************************************************"
-            echo "*                                                                 *"
-            echo "*ERROR: ntop requires automake version 1.6 or newer...            *"
-            echo "*                                                                 *"
-            echo "*  You are executing ${automakeversion}"
-            echo "*                                                                 *"
-            echo "*>>>   Unable to proceed with your request, aborting ./configure! *"
-            echo "*                                                                 *"
-            echo "*???    Suggestion - Install a private copy of automake 1.6.3.    *"
-            echo "*???                 It's quite easy and does NOT require root:   *"
-            echo "*                                                                 *"
-            echo "*   Download automake 1.6.3 from gnu                              *"
-            echo "*     $ wget http://ftp.gnu.org/gnu/automake/automake-1.6.3.tar.gz*"
-            echo "*                                                                 *"
-            echo "*   Untar it                                                      *"
-            echo "*     $ tar xfvz automake-1.6.3.tar.gz                            *"
-            echo "*                                                                 *"
-            echo "*   Make it                                                       *"
-            echo "*     $ cd automake-1.6.3                                         *"
-            echo "*     $ ./configure --prefix=/home/<whatever>/automake163         *"
-            echo "*     $ make                                                      *"
-            echo "*     $ make install                                              *"
-            echo "*                                                                 *"
-            echo "*   Add it to your path.  Under bash do this:                     *"
-            echo "*     $ PATH=/home/<whatever>automake163/bin:\$PATH                *"
-            echo "*     $ export PATH                                               *"
-            echo "*                                                                 *"
-            echo "*******************************************************************"
-            exit 1
-            ;;
-    esac
-
     echo "  Invoking automake to copy depcomp..."
     automake --gnu --copy --add-missing
     echo ""
 
 fi
-
-
-for ac_prog in gawk mawk nawk awk
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_AWK+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$AWK"; then
-  ac_cv_prog_AWK="$AWK" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_AWK="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-AWK=$ac_cv_prog_AWK
-if test -n "$AWK"; then
-  echo "$as_me:$LINENO: result: $AWK" >&5
-echo "${ECHO_T}$AWK" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$AWK" && break
-done
 
 
 # Check whether --enable-void or --disable-void was given.
@@ -30476,6 +30476,7 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
+s,@AWK@,$AWK,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
@@ -30503,7 +30504,6 @@ s,@install_sh@,$install_sh,;t t
 s,@STRIP@,$STRIP,;t t
 s,@ac_ct_STRIP@,$ac_ct_STRIP,;t t
 s,@INSTALL_STRIP_PROGRAM@,$INSTALL_STRIP_PROGRAM,;t t
-s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -48,7 +48,7 @@ dnl>       into the stamp.
 dnl>
 AC_INIT([ntop],[2.1.56pre])
 AC_PREREQ([2.50])
-SCRIPTVER="v1.100-2003-01-29"
+SCRIPTVER="v1.101-2003-01-31"
 
 dnl>
 dnl> generate the config header
@@ -82,8 +82,101 @@ echo "Configuring ${PACKAGE_NAME} according to your request(s):"
 echo "   ./configure ${CONFIGURE_PARAMETERS}"
 echo
 
+echo "*******************************************************************"
+echo "*                                                                 *"
+echo "* NOTICE:  I know you're used to ignoring output from ./configure *"
+echo "*                                                                 *"
+echo "*          ntop has a lot of complexity and interdependences.     *"
+echo "*                                                                 *"
+echo "*          Please, please AT LEAST read the stuff in these        *"
+echo "*          boxes!                                                 *"
+echo "*                                                                 *"
+echo "*>>> The ACTION taken is shown prefixed '>>>'                     *"
+echo "*                                                                 *"
+echo "*    If the ACTION is unacceptable,                               *"
+echo "*??? The REMEDIATION plan is shown prefixed with '???'            *"
+echo "*                                                                 *"
+echo "*******************************************************************"
+echo
+
+dnl> early since we need it for --enable-showoses and autotool version check.
+AC_PROG_AWK
+
 dnl>
-dnl> Check versions of autotools...
+dnl> Check versions of autotools
+
+dnl> First check minimum versions...
+echo "  Checking automake version..."
+automakeversion=`automake --version | grep ^automake | awk '{ print $4 }'`
+case "${automakeversion}" in
+    *1\.[[0-5]]*)
+        echo "*******************************************************************"
+        echo "*                                                                 *"
+        echo "*ERROR: ntop requires automake version 1.6 or newer...            *"
+        echo "*                                                                 *"
+        echo "*  You are executing ${automakeversion}"
+        echo "*                                                                 *"
+        echo "*>>>   Unable to proceed with your request, aborting ./configure! *"
+        echo "*                                                                 *"
+        echo "*???    Suggestion - Install a private copy of automake 1.6.3.    *"
+        echo "*???                 It's quite easy and does NOT require root:   *"
+        echo "*                                                                 *"
+        echo "*   Download automake 1.6.3 from gnu                              *"
+        echo "*     $ wget http://ftp.gnu.org/gnu/automake/automake-1.6.3.tar.gz*"
+        echo "*                                                                 *"
+        echo "*   Untar it                                                      *"
+        echo "*     $ tar xfvz automake-1.6.3.tar.gz                            *"
+        echo "*                                                                 *"
+        echo "*   Make it                                                       *"
+        echo "*     $ cd automake-1.6.3                                         *"
+        echo "*     $ ./configure --prefix=/home/<whatever>/automake163         *"
+        echo "*     $ make                                                      *"
+        echo "*     $ make install                                              *"
+        echo "*                                                                 *"
+        echo "*   Add it to your path.  Under bash do this:                     *"
+        echo "*     $ PATH=/home/<whatever>automake163/bin:\$PATH                *"
+        echo "*     $ export PATH                                               *"
+        echo "*                                                                 *"
+        echo "*******************************************************************"
+        exit 1
+        ;;
+esac
+echo "  Checking autoconf version..."
+case "${autoconfversion}" in
+    *2\.[[0-4]]*)
+        echo "*******************************************************************"
+        echo "*                                                                 *"  
+        echo "*ERROR: ntop requires autoconf version 2.50 or newer...           *"  
+        echo "*                                                                 *"  
+        echo "*  You are executing ${autoconfversion}"
+        echo "*                                                                 *"  
+        echo "*>>>   Unable to proceed with your request, aborting ./configure! *"
+        echo "*                                                                 *"  
+        echo "*???    Suggestion - Install a private copy of autoconf 2.5x.     *"  
+        echo "*???                 It's quite easy and does NOT require root:   *"  
+        echo "*                                                                 *"  
+        echo "*   Download autoconf 2.57 from gnu                               *"  
+        echo "*     $ wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.57.tar.gz *"
+        echo "*                                                                 *"  
+        echo "*   Untar it                                                      *"  
+        echo "*     $ tar xfvz autoconf-2.57.tar.gz                             *"  
+        echo "*                                                                 *"  
+        echo "*   Make it                                                       *"  
+        echo "*     $ cd autoconf-2.57                                          *"  
+        echo "*     $ ./configure --prefix=/home/<whatever>/autoconf257         *"  
+        echo "*     $ make                                                      *"  
+        echo "*     $ make install                                              *"  
+        echo "*                                                                 *"  
+        echo "*   Add it to your path.  Under bash do this:                     *"  
+        echo "*     $ PATH=/home/<whatever>autoconf257/bin:\$PATH                *"  
+        echo "*     $ export PATH                                               *"  
+        echo "*                                                                 *"
+        echo "*******************************************************************"
+        exit 1
+        ;;
+esac
+
+dnl> Then check for a match with the scripts...
 dnl>
 dnl>      We know that all of the 1.6.x [1..3] versions of automake work ok
 dnl>      and the 2.5x [1..7] of autoconf work ok too.
@@ -93,9 +186,9 @@ dnl>
 if test -f /tmp/autotoolversions; then
      rm -f /tmp/autotoolversions
 fi
-automake --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }'  >/tmp/autotoolversions
-autoconf --version | head -n 1 | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
-libtool --version | head -n 1  | awk '{ gsub(/)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+automake --version | head -n 1 | ${ac_cv_prog_AWK} '{ gsub(/\)/, "", $3); print "     " $3 " " $4 }'  >/tmp/autotoolversions
+autoconf --version | head -n 1 | ${ac_cv_prog_AWK} '{ gsub(/\)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
+libtool --version | head -n 1  | ${ac_cv_prog_AWK} '{ gsub(/\)/, "", $3); print "     " $3 " " $4 }' >>/tmp/autotoolversions
 
 touch autotoolversions
 diff -q autotoolversions /tmp/autotoolversions 2>/dev/null
@@ -121,7 +214,7 @@ if test ".${rc}" = ".1"; then
     echo "*>>>     2. use the auto* tools to recreate them"
     echo "*                (if you do not have automake, autoconf and libtool"
     echo "*                 intalled, this will fail)"
-    echo "*>>>     3. tell you to rerun ./configure with the --enable-automake171 flag"
+    echo "*>>>     3. tell you to rerun ./configure"
     echo "*"
     echo "*    Please, tell the ntop-dev mailing list if there are problems..."
     echo "*"
@@ -189,10 +282,15 @@ if test ".${rc}" = ".1"; then
     fi
 
     echo
-    echo
-    echo "Now, rerun ./configure"
+    echo "*******************************************************************"
+    echo "*                                                                 *"
+    echo "*   Now, rerun ./configure                                        *"
+    echo "*                                                                 *"
+    echo "*******************************************************************"
     echo
     exit 1
+else
+    echo "auto* tools are OK, continuing with ./configure"
 fi
 
 dnl> autoheader stuff...just ignore
@@ -207,23 +305,6 @@ AH_TEMPLATE([HAVE_U_INT64_T], [Define for unsigned int 64 typedef])
 AH_TEMPLATE([HAVE_U_INT8_T],  [Define for unsigned int 8 typedef])
 AH_TEMPLATE([HAVE_LIBWRAP],   [Define for tcp wrappers (-lwrap)])
 dnl> end autoheader stuff
-
-echo "*******************************************************************"
-echo "*                                                                 *"
-echo "* NOTICE:  I know you're used to ignoring output from ./configure *"
-echo "*                                                                 *"
-echo "*          ntop has a lot of complexity and interdependences.     *"
-echo "*                                                                 *"
-echo "*          Please, please AT LEAST read the stuff in these        *"
-echo "*          boxes!                                                 *"
-echo "*                                                                 *"
-echo "*>>> The ACTION taken is shown prefixed '>>>'                     *"
-echo "*                                                                 *"
-echo "*    If the ACTION is unacceptable,                               *"
-echo "*??? The REMEDIATION plan is shown prefixed with '???'            *"
-echo "*                                                                 *"
-echo "*******************************************************************"
-echo
 
 dnl> Basic sanity check ... does ntop.c exist?
 AC_CONFIG_SRCDIR([ntop.c])
@@ -246,49 +327,10 @@ AC_CHECK_FILE(depcomp, , [
 
     echo ""
     echo "depcomp missing... will install it in this ntop directory."
-    echo "  Checking automake version..."
-    automakeversion=`automake --version | grep ^automake | awk '{ print $4 }'`
-    case "${automakeversion}" in
-        *1\.[[45]]*)
-            echo "*******************************************************************"
-            echo "*                                                                 *"
-            echo "*ERROR: ntop requires automake version 1.6 or newer...            *"
-            echo "*                                                                 *"
-            echo "*  You are executing ${automakeversion}"
-            echo "*                                                                 *"
-            echo "*>>>   Unable to proceed with your request, aborting ./configure! *"
-            echo "*                                                                 *"
-            echo "*???    Suggestion - Install a private copy of automake 1.6.3.    *"
-            echo "*???                 It's quite easy and does NOT require root:   *"
-            echo "*                                                                 *"
-            echo "*   Download automake 1.6.3 from gnu                              *"
-            echo "*     $ wget http://ftp.gnu.org/gnu/automake/automake-1.6.3.tar.gz*"
-            echo "*                                                                 *"
-            echo "*   Untar it                                                      *"
-            echo "*     $ tar xfvz automake-1.6.3.tar.gz                            *"
-            echo "*                                                                 *"
-            echo "*   Make it                                                       *"
-            echo "*     $ cd automake-1.6.3                                         *"
-            echo "*     $ ./configure --prefix=/home/<whatever>/automake163         *"
-            echo "*     $ make                                                      *"
-            echo "*     $ make install                                              *"
-            echo "*                                                                 *"
-            echo "*   Add it to your path.  Under bash do this:                     *"
-            echo "*     $ PATH=/home/<whatever>automake163/bin:\$PATH                *"
-            echo "*     $ export PATH                                               *"
-            echo "*                                                                 *"
-            echo "*******************************************************************"
-            exit 1 
-            ;;
-    esac
-
     echo "  Invoking automake to copy depcomp..."
     automake --gnu --copy --add-missing
     echo ""
 ])
-
-dnl> early since we need it for --enable-showoses
-AC_PROG_AWK
 
 AC_ARG_ENABLE(void,
               [  +--ntop-specific:------------------------------------------------------------+])
