Lots of improvements - esp. WRT Debian's children and FreeBSD. -----Burton

diff --git a/utils/linuxrelease b/utils/linuxrelease
--- a/utils/linuxrelease
+++ b/utils/linuxrelease
@@ -1,13 +1,13 @@
-#!/bin/sh
+#!/bin/bash
 
-#  Copyright (c) 2003, Burton M. Strauss III - Burton@ntopsupport.com
+#  Copyright (c) 2003-2005, Burton M. Strauss III - Burton@ntopsupport.com
 
 #
 #  Return the distro name, release # or both...
 #
 #    Crude, but marginally effective, uses the /etc/xxxxxx-release file.
 #
-#    Tested:   RH 7.2 7.3, 8.0, 9, 2.1AS 2.1ES, 3.0AS, 3.0ES
+# V1 Tested:   RH 7.2 7.3, 8.0, 9, 2.1AS 2.1ES, 3.0AS, 3.0ES
 #              Fedora Core 1, 2, 3
 #              Mandrake 9.1, 10, 10.1
 #              Debian 2.2 3.0(Woody)
@@ -17,6 +17,16 @@
 #              LFS (Linux From Scratch)
 #              FreeBSD 4.9, 4.10, 5.2, 5.3
 #              NetBSD 1.6
+# V2 Tested:
+#              DamnSmallLinux 0.9.0, 0.9.2
+#              Debian 3.0r3, 3.1
+#              Fedora Core 2, 3
+#              FreeBSD 4.11, 5.3
+#              Gentoo 2005.0
+#              Knoppix 3.7
+#              RedHat 8.0
+#              SuSE 8.0ES, 9.0, 9.2
+#              Ubuntu 5.04
 #
 
 #  Released under GPL...
@@ -36,60 +46,25 @@
 #    Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
-debug="N"
-if test "x${1}" = "x--debug"; then
-    debug="Y"
-    shift
-fi
-
-quiet="N"
-if test "x${1}" = "x--quiet"; then
-    quiet="Y"
-    shift
-fi
-
-# Is this even Linux??
-case `uname -s` in
-  [Ll]inux*)
-    kernel=`uname -r`
-
-    # First, check for a /etc/xxxxx-release file...
-    releaseFile=`find /etc -type f -name "*-release" -maxdepth 1 2> /dev/null | \
-                 grep -v lsb | \
-                 grep -v UnitedLinux | \
-                 head -n 1`
-    if test "x${debug}" = "xY"; then
-        echo "DEBUG01: /etc/xxxxx-release found ${releaseFile}"
-    fi
-    
-    # Not found?  Maybe there's a /etc/xxxxxx-version file (Slackware)
-    if test "x${releaseFile}" = "x"; then
-        releaseFile=`find /etc -type f -name "*-version" -maxdepth 1 2> /dev/null | \
-                     head -n 1`
+function checkForKeyFile() {
+    # The tests for release, version etc. file...
+    for testme in fedora-release *-release *version lfs-*; do
+      releaseFile=`find /etc -name "${testme}" ${maxdepth} 2> /dev/null | \
+                   grep -v lsb | \
+                   grep -v UnitedLinux | \
+                   head -n 1` 
+      if test "x${releaseFile}" != "x"; then
         if test "x${debug}" = "xY"; then
-            echo "DEBUG02: /etc/xxxxx-version found ${releaseFile}"
+          echo "DEBUG01: /etc found ${releaseFile}"
         fi
-    fi
-    # Not found?  Maybe there's a /etc/xxxxxx_version file (Debian)
-    if test "x${releaseFile}" = "x"; then
-        releaseFile=`find /etc -type f -name "*_version" -maxdepth 1 2> /dev/null | \
-                     head -n 1`
-        if test "x${debug}" = "xY"; then
-            echo "DEBUG03: /etc/xxxxx_version found ${releaseFile}"
-        fi
-    fi
-    # Not found?  Maybe there's a /etc/lfs-xxxxxx file
-    if test "x${releaseFile}" = "x"; then
-        releaseFile=`find /etc -type f -name "lfs-*" -maxdepth 1 2> /dev/null | \
-                     head -n 1`
-        if test "x${debug}" = "xY"; then
-            echo "DEBUG03: /etc/lfs-xxxxx found ${releaseFile}"
-        fi
-    fi
-    
-    
+        return
+      fi
+    done
+}
+
+function checkForStandards() {
     # Check for the 'standards' bodies id files...
-    lsbFile=`find /etc -type f -name "lsb-release" -maxdepth 1 2> /dev/null | \
+    lsbFile=`find /etc -name "lsb-release" ${maxdepth} 2> /dev/null | \
              head -n 1`
     if test "x${debug}" = "xY"; then
         echo "DEBUG04: /etc/lsb-release found ${lsbFile}"
@@ -109,7 +84,7 @@ case `uname -s` in
         lsbrelease="Not identified as LSB compliant"
     fi
     
-    unitedFile=`find /etc -type f -name "UnitedLinux-release" -maxdepth 1 | \
+    unitedFile=`find /etc -name "UnitedLinux-release" ${maxdepth} 2> /dev/null | \
                 head -n 1`
     if test "x${debug}" = "xY"; then
         echo "DEBUG06: /etc/UnitedLinux-release found ${unitedFile}"
@@ -129,6 +104,202 @@ case `uname -s` in
     else
         unitedrelease="Not identified as UnitedLinux compliant"
     fi
+}
+
+function checkEtcIssue() {    
+    # Try /etc/issue...
+    eirelease=`awk '{ for(i=1; i<=NF; i++) { if((0+$i) != 0) { print $i; exit 0 } } }' /etc/issue`
+    if test "x${debug}" = "xY"; then
+      echo "DEBUG20: /etc/issue gives ${eirelease}"
+    fi
+    eidistro=`awk '{ print $1; exit 0 }' /etc/issue`
+    if test "x${debug}" = "xY"; then
+      echo "DEBUG21: /etc/issue gives ${eidistro}"
+    fi
+
+    if test "x${releaseFile}" = "x"; then
+      release="${eirelease}"
+      distro="${eidistro}"
+      releaseFile="/etc/issue"
+      if test "x${debug}" = "xY"; then
+        echo "DEBUG22: /etc/issue sets distro/release/releaseFile"
+      fi
+      return
+    fi
+
+    if test "x${release}" = "x"; then
+      if test "x${eirelease}" != "x"; then
+        release="${eirelease}"
+        if test "x${debug}" = "xY"; then
+          echo "DEBUG23: /etc/issue sets release"
+        fi
+      fi
+    fi
+    if test "x${distro}" = "x"; then
+      if test "x${eidistro}" != "x"; then
+        distro="${eidistro}"
+        if test "x${debug}" = "xY"; then
+          echo "DEBUG24: /etc/issue sets distro"
+        fi
+      fi
+    fi
+}
+
+function processReleaseFile() {
+
+    if test "x${releaseFile}" = "x/etc/issue"; then
+      return
+    fi
+
+    # Grab the distro name...
+    distro=`echo ${releaseFile} | \
+            awk '{ i=index($0, "_"); \
+                   if (i == 0) { \
+                       i=index($0, "-") \
+                   }; \
+                   print tolower(substr($0, 6, i-6)) \
+                 }'`
+    if test "x${debug}" = "xY"; then
+        echo "DEBUG11: Distribution is ${distro}"
+    fi
+
+    # Check if the file is readable for a release name?
+    if test -s ${releaseFile}; then
+    
+        # Grab the full release name text
+        fullrelease=`cat ${releaseFile} | \
+                     head -n 1`
+        if test "x${debug}" = "xY"; then
+            echo "DEBUG12: fullrelease is ${fullrelease}"
+        fi
+    
+        # Grab the release name
+        release=`cat ${releaseFile} | \
+                 head -n 1 | \
+                 awk '{ i=index($0, "("); if(i>0) { $0 = substr($0, 1, i-1) }; for (i=1; i<=NF; i++) { if (0 + $i != 0) { print $i } } }'`
+    
+        if test "x${release}" = "x"; then
+            if test "x${debug}" = "xY"; then
+                echo "DEBUG13: (alt) Scanning for VERSION in ${releaseFile}"
+            fi
+            release=`cat ${releaseFile} | \
+                     grep -i VERSION | \
+                     head -n 1 | \
+                     awk '{ i=index($0, "("); if(i>0) { $0 = substr($0, 1, i-1) }; for (i=1; i<=NF; i++) { if (0 + $i != 0) { print $i } } }'`
+        fi
+    
+        if test "x${release}" = "x"; then
+            if test "x${debug}" = "xY"; then
+                echo "DEBUG14: (alt) Executing set commands in ${releaseFile}"
+            fi
+            . ${releaseFile} 2> /dev/null
+            release="${VERSION}"
+        fi
+    
+        if test "x${release}" = "x"; then
+            release="unknown"
+            if test "x${debug}" = "xY"; then
+                echo "DEBUG15: Unable to identify release"
+            fi
+        else
+            if test "x${debug}" = "xY"; then
+                echo "DEBUG16: Release is ${release}"
+            fi
+        fi
+
+        return
+    fi
+    
+    # Can't grab the release name, so maybe it's in the filename?
+    release=`echo ${releaseFile} | \
+           awk '{ i=index($0, "_"); \
+                   if (i == 0) { \
+                       i=index($0, "-") \
+                   }; \
+                   if (i == 0) { \
+                       print "" \
+                   } else \
+                       print tolower(substr($0, i+1)) \
+                }'`
+
+    if test "x${release}" = "x"; then
+        # else return unknown
+        release="unknown"
+        if test "x${debug}" = "xY"; then
+            echo "DEBUG17: File unreadable, release unknown"
+        fi
+    fi
+
+    return
+}
+
+function processDebianDerivatives() {    
+    # Debian derivatives...
+    if test "${distro}x" = "debianx"; then
+      if test "x${debug}" = "xY"; then
+        echo "DEBUG18: Debian derivatives... distro ${distro} release ${release} full ${fullrelease}..."
+      fi
+      baserelease=" (base: ${distro} ${release})"
+      # DamnSmall Linux? /usr/share/doc/dsl directory...
+      if test -d /usr/share/doc/dsl; then
+        distro="DamnSmallLinux" 
+        if test -r /usr/share/doc/dsl/getting_started.html; then
+          release=`awk '{ i=index($0, "Version"); if(i == 0) { next }; $0 = substr($0, i+7); i=index($0, "<"); if(i == 0) { next }; $0=substr($0, 1, i-1); print $1; exit 0; }' /usr/share/doc/dsl/getting_started.html` 
+          if test "x${debug}" = "xY"; then
+            echo "DEBUG19: DamnSmallLinux release is ${release}"
+          fi
+        fi
+        fullrelease="${distro} ${release}${baserelease}"
+        return
+      fi
+
+      if test -d /KNOPPIX; then
+        distro="Knoppix"
+        release="unknown"
+        fullrelease="${distro} ${release}${baserelease}"
+        return
+      fi
+
+      if test "x${eirelease}" != "x"; then
+        if test "x${eirelease}" != "x${release}"; then
+          # /etc/issue different ... use that...
+          release="${eirelease}"
+          distro="${eidistro}"
+          fullrelease="${distro} ${release}${baserelease}"
+          return
+        fi
+      fi
+    fi
+}
+
+debug="N"
+if test "x${1}" = "x--debug"; then
+    debug="Y"
+    shift
+fi
+
+quiet="N"
+if test "x${1}" = "x--quiet"; then
+    quiet="Y"
+    shift
+fi
+
+find . -maxdepth 1 >/dev/null 2>/dev/null
+rc=$?
+if test $rc -eq 0; then
+  maxdepth=" -maxdepth 1"
+else
+  maxdepth=""
+fi
+
+# Is this even Linux??
+case `uname -s` in
+  [Ll]inux*)
+    kernel=`uname -r`
+
+    checkForKeyFile
+
+    checkForStandards
     
     # Now if we're still not found, let's use the standards bodies files... if we have 'em
     if test "x${releaseFile}" = "x"; then
@@ -144,7 +315,9 @@ case `uname -s` in
             fi
         fi
     fi
-    
+
+    checkEtcIssue
+
     # Still not found?  Um... unknown...
     if test "x${releaseFile}" = "x"; then
         distro="Linux"
@@ -153,92 +326,15 @@ case `uname -s` in
             echo "DEBUG10: Unknown linux release"
         fi
     else
-        # Grab the distro name...
-        distro=`echo ${releaseFile} | \
-                awk '{ i=index($0, "_"); \
-                       if (i == 0) { \
-                           i=index($0, "-") \
-                       }; \
-                       print tolower(substr($0, 6, i-6)) \
-                     }'`
-        if test "x${debug}" = "xY"; then
-            echo "DEBUG11: Distribution is ${distro}"
-        fi
-    
-        # Check if the file is readable for a release name?
-        if test -s ${releaseFile}; then
-    
-            # Grab the full release name text
-            fullrelease=`cat ${releaseFile} | \
-                         head -n 1`
-            if test "x${debug}" = "xY"; then
-                echo "DEBUG12: fullrelease is ${fullrelease}"
-            fi
-    
-    
-            # Grab the release name
-            release=`cat ${releaseFile} | \
-                     head -n 1 | \
-                     awk '{ i=index($0, "("); if(i>0) { $0 = substr($0, 1, i-1) }; for (i=1; i<=NF; i++) { if (0 + $i != 0) { print $i } } }'`
-    
-            if test "x${release}" = "x"; then
-                if test "x${debug}" = "xY"; then
-                    echo "DEBUG13: (alt) Scanning for VERSION in ${releaseFile}"
-                fi
-                release=`cat ${releaseFile} | \
-                         grep -i VERSION | \
-                         head -n 1 | \
-                         awk '{ i=index($0, "("); if(i>0) { $0 = substr($0, 1, i-1) }; for (i=1; i<=NF; i++) { if (0 + $i != 0) { print $i } } }'`
-            fi
-    
-            if test "x${release}" = "x"; then
-                if test "x${debug}" = "xY"; then
-                    echo "DEBUG14: (alt) Executing set commands in ${releaseFile}"
-                fi
-                . ${releaseFile} 2> /dev/null
-                release="${VERSION}"
-            fi
-    
-            if test "x${release}" = "x"; then
-                release="unknown"
-                if test "x${debug}" = "xY"; then
-                    echo "DEBUG15: Unable to identify release"
-                fi
-            else
-                if test "x${debug}" = "xY"; then
-                    echo "DEBUG16: Release is ${release}"
-                fi
-            fi
-    
-        else
-    
-            # Can't grab the release name, so maybe it's in the filename?
-            release=`echo ${releaseFile} | \
-                   awk '{ i=index($0, "_"); \
-                           if (i == 0) { \
-                               i=index($0, "-") \
-                           }; \
-                           if (i == 0) { \
-                               print "" \
-                           } else \
-                               print tolower(substr($0, i+1)) \
-                        }'`
-
-            if test "x${release}" = "x"; then
-                # else return unknown
-                release="unknown"
-                if test "x${debug}" = "xY"; then
-                    echo "DEBUG17: File unreadable, release unknown"
-                fi
-            fi
-        fi
+        processReleaseFile
     fi
+
+    processDebianDerivatives
+
     ;;
+
   [Ff][Rr][Ee][Ee][Bb][Ss][Dd])
     # FreeBSD
-    if test "x${quiet}" != "xY"; then
-        echo "WARNING: This routine only works under Linux.  We'll fake it as best we can!"
-    fi
     distro=`uname -s`
     release=`uname -r`
     kernel=`uname -i 2> /dev/null`
@@ -258,10 +354,11 @@ case `uname -s` in
     lsbrelease="Not Linux - not LSB compliant"
     unitedrelease="Not Linux - not UnitedLinux compliant"
     ;;
+
   *)
     # Not Linux - oops
     if test "x${quiet}" != "xY"; then
-        echo "WARNING: This routine only works under Linux.  We'll fake it as best we can!"
+        echo "WARNING: This routine only works under Linux/FreeBSD.  We'll fake it as best we can!"
     fi
     distro=`uname -s`
     release=`uname -r`
@@ -295,11 +392,11 @@ case "${1}" in
        echo
        echo "Usage: linuxrelease [--distro] [--[united|lsb|full]release] [--kernel] [--help]"
        echo
-       echo "  Uses the /etc/xxxxx-release or /etc/xxxxx_version file to figure out "
+       echo "  Uses the /etc/xxxxx-release or /etc/xxxxx_version or other files to figure out "
        echo "  a decent guess as to which Linux distro and release this is..."
        echo
     ;;
   *)
-    echo ${distro} ${release} ${kernel}
+    echo ${distro} release ${release} kernel ${kernel}
     ;;
 esac
